### ISSUE TITLE
Installing secp256k1 on Mac(Apple sillicon chip) fails

### ISSUE THREAD

**Issue by gterzian** [massalabs/massa-network-simulator#35]
With the following error. 

```
The package setup script has attempted to modify files on your system
      that are not within the EasyInstall build area, and has been aborted.
      
      This package cannot be safely installed by EasyInstall, and may not
      support alternate installation locations even if you run its setup
      script by hand.  Please inform the package's author and the EasyInstall
      maintainers to find out if a fix or workaround is available.
```

Have you encountered this and come up with a solution?

**Comment by AurelienFT** [comment]
We don't use this module anymore. The import that left in charge.py is legacy and never used you can remove it.

**Comment by damip** [comment]
> We don't use this module anymore. The import that left in charge.py is legacy and never used you can remove it.

we should push all those corrections and add a readme for everyone to be able to easily use the tool
